development:
  adapter: postgresql
  encoding: unicode
  database: example_admin_development
  pool: 5
  username: jamesnewman
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: example_admin_test
  pool: 5
  username: jamesnewman
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: example_admin_production
  pool: 5
  username: jamesnewman
  password: password